## GitHub Actions Workflow - Demo CI/CD Workflow dev

# This GitHub Actions workflow is responsible for the CI/CD pipeline for the development environment.
# It triggers on workflow dispatch and push events on specific branches.
# This job uses the template_deploy.yaml workflow file to deploy the application to the development environment.
# - **Environment**: dev
# - **Secrets**:
#  - AWS_ACCESS_KEY_ID: Access key for AWS authentication
#  - AWS_SECRET_ACCESS_KEY: Secret key for AWS authentication
name: Demo CI/CD Workflow dev
on:
  workflow_dispatch:
  push:
    branches:
        - "**"

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/template_deploy.yml
    with:
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_REGION: ${{ secrets.AWS_REGION_DEV }}

